### PR TITLE
Add size and null methods

### PR DESCRIPTION
**Pull request by Fuuzetsu**
Also stack.yaml so I could actually build this.

### CODE REVIEW

**Comment by takano-akio** [comment]
You should be able to use `length` and `null` from `Foldable`, which is a transitive superclass of `Maplike`.

**Comment by Fuuzetsu** [comment]
Oh. That works I guess. I also realised the Strict/Lazy modules already available too. Thanks.

**Comment by takano-akio** [comment]
I'll take the changes other than the addition of the methods.

**Comment by Fuuzetsu** [comment]
Here you go https://github.com/takano-akio/maplike/pull/3

**Pull request closed without merging**
